pub mod cli;
pub mod config;
pub mod db;
pub mod error;
pub mod generator;
pub mod mcp;
pub mod migration;
pub mod minimizer;
pub mod report;
pub mod schema;
pub mod search;
pub mod semantic;
pub mod storage;
pub mod strategy;

pub use config::FaultlineConfig;
pub use db::PgClient;
pub use error::{FaultlineError, Result};
pub use generator::{DatabaseState, RowData, SqlValue, TableData};
pub use mcp::McpServer;
pub use migration::{MigrationResult, MigrationRunner};
pub use minimizer::Minimizer;
pub use report::{CounterexampleReplayer, ReportGenerator};
pub use schema::DatabaseSchema;
pub use search::{SearchBudget, SearchEngine, SearchSummary};
pub use storage::{CounterexampleArtifact, CounterexampleManifest, StorageManager};
pub use strategy::{SearchStrategy, StrategyScheduler};
